import {
  AssignmentGrade,
  AssignmentStatus,
  AssignmentType,
  BeatAssigneeRole,
  BeatStatus,
  IdeaRank,
  IdeaStatus,
  PersonRole,
  ProductionType,
  PrismaClient,
} from "@prisma/client";

const prisma = new PrismaClient();

const writers = [
  "Ari Jacobson",
  "Carolina Munhoz",
  "Cory David Crouser",
  "Jasper Chen",
  "Joe Osborn",
  "Jonathan Hernandez",
  "Krystle Drew",
  "Micah McFarland",
  "Michael Ouzas",
  "Miguel Silan",
  "Minoti Vaishnav",
  "Nandita Seshadri",
  "Will Morgan",
  "William Heus",
];

const podLeads = ["Dan Woodward", "Joshua Roth", "Nishant Gilatar", "Paul Lee"];
const business = ["Aakash Ahuja", "Jacob Berman", "Lux Saxena", "Pranav Patki", "Yadhu Gopal"];

function dateOnly(value: string) {
  return new Date(`${value}T12:00:00.000Z`);
}

function timestamp(value: string) {
  return new Date(value);
}

async function main() {
  await prisma.assignment.deleteMany();
  await prisma.beat.deleteMany();
  await prisma.idea.deleteMany();
  await prisma.person.deleteMany();
  await prisma.workflowCounter.deleteMany();

  for (const name of writers) {
    await prisma.person.create({
      data: {
        name,
        role: PersonRole.WRITER,
      },
    });
  }

  for (const name of podLeads) {
    await prisma.person.create({
      data: {
        name,
        role: PersonRole.POD_LEAD,
      },
    });
  }

  for (const name of business) {
    await prisma.person.create({
      data: {
        name,
        role: PersonRole.BUSINESS,
      },
    });
  }

  await prisma.workflowCounter.createMany({
    data: [
      { key: "IDEA", value: 10 },
      { key: "BEAT", value: 8 },
      { key: "ASSIGNMENT", value: 10 },
    ],
  });

  const people = await prisma.person.findMany();
  const personByName = new Map(people.map((person) => [person.name, person.id]));

  const ideas = [
    {
      code: "I0001",
      show: "MVS",
      angle: "Why Sleep Deprivation Is the Silent Productivity Killer",
      submittedByName: "Jonathan Hernandez",
      submittedOn: "2026-01-05",
      status: IdeaStatus.ACCEPTED,
      rank: IdeaRank.HIGH_CONVICTION,
      setting: "Corporate workplace",
      opening: "We treat sleep as optional but science says otherwise",
      tickingClock: "Every bad night compounds cognitive debt silently",
      stakes: "Performance, decision quality, long-term health",
      goal: "Connect sleep science to measurable workplace output",
      cliffhanger: "What if sleep is the most neglected productivity lever?",
      note: "NA",
    },
    {
      code: "I0002",
      show: "FLBM",
      angle: "The Hidden Cost of Always Being Available",
      submittedByName: "Nandita Seshadri",
      submittedOn: "2026-01-06",
      status: IdeaStatus.ACCEPTED,
      rank: IdeaRank.HIGH_CONVICTION,
      setting: "Always-on remote work culture",
      opening: "The notification that never stops is rewiring your brain",
      tickingClock: "Burnout rates are doubling year over year",
      stakes: "Mental health, retention, creative output",
      goal: "Quantify the true cost of constant availability",
      cliffhanger: "What if being less available made you more effective?",
      note: "NA",
    },
    {
      code: "I0003",
      show: "WBT",
      angle: "Decision Fatigue: Why Leaders Make Worse Choices After Noon",
      submittedByName: "Dan Woodward",
      submittedOn: "2026-01-07",
      status: IdeaStatus.NOT_REVIEWED,
      rank: IdeaRank.UNRANKED,
      setting: "NA",
      opening: "NA",
      tickingClock: "NA",
      stakes: "NA",
      goal: "NA",
      cliffhanger: "NA",
      note: "NA",
    },
    {
      code: "I0004",
      show: "MVS",
      angle: "How Micro-Habits Compound Into Major Behavioral Shifts",
      submittedByName: "Ari Jacobson",
      submittedOn: "2026-01-08",
      status: IdeaStatus.NOT_REVIEWED,
      rank: IdeaRank.BET,
      setting: "NA",
      opening: "NA",
      tickingClock: "NA",
      stakes: "NA",
      goal: "NA",
      cliffhanger: "NA",
      note: "NA",
    },
    {
      code: "I0005",
      show: "FLBM",
      angle: "The Science of First Impressions in Professional Settings",
      submittedByName: "Krystle Drew",
      submittedOn: "2026-01-09",
      status: IdeaStatus.NOT_REVIEWED,
      rank: IdeaRank.BET,
      setting: "NA",
      opening: "NA",
      tickingClock: "NA",
      stakes: "NA",
      goal: "NA",
      cliffhanger: "NA",
      note: "NA",
    },
    {
      code: "I0006",
      show: "WBT",
      angle: "What Cold Water Swimming Teaches Us About Stress Tolerance",
      submittedByName: "Miguel Silan",
      submittedOn: "2026-01-10",
      status: IdeaStatus.ACCEPTED,
      rank: IdeaRank.HIGH_CONVICTION,
      setting: "Biohacking and wellness space",
      opening: "Your body has a built-in stress reset — most people never use it",
      tickingClock: "Chronic stress is eroding nervous system resilience daily",
      stakes: "Mental resilience, physical recovery, stress response",
      goal: "Make cold exposure accessible and scientifically grounded",
      cliffhanger: "Could 3 minutes change your entire stress response?",
      note: "NA",
    },
    {
      code: "I0007",
      show: "MVS",
      angle: "Reading Between the Lines: What Body Language Reveals in Negotiation",
      submittedByName: "Paul Lee",
      submittedOn: "2026-01-11",
      status: IdeaStatus.NOT_REVIEWED,
      rank: IdeaRank.UNRANKED,
      setting: "NA",
      opening: "NA",
      tickingClock: "NA",
      stakes: "NA",
      goal: "NA",
      cliffhanger: "NA",
      note: "NA",
    },
    {
      code: "I0008",
      show: "FLBM",
      angle: "The Myth of the 10,000 Hour Rule Revisited",
      submittedByName: "Jasper Chen",
      submittedOn: "2026-01-12",
      status: IdeaStatus.REJECTED,
      rank: IdeaRank.REJECT,
      setting: "Skill development and mastery",
      opening: "You've been told 10,000 hours makes you an expert — that's only half the story",
      tickingClock: "People are investing years in the wrong kind of practice",
      stakes: "Career trajectory, competitive edge, time investment",
      goal: "Reframe deliberate practice vs repetition with evidence",
      cliffhanger: "Are you practicing — or just putting in time?",
      note: "Revisit framing",
    },
    {
      code: "I0009",
      show: "WBT",
      angle: "Why Your Morning Routine Might Be Working Against You",
      submittedByName: "Minoti Vaishnav",
      submittedOn: "2026-01-13",
      status: IdeaStatus.NOT_REVIEWED,
      rank: IdeaRank.BET,
      setting: "NA",
      opening: "NA",
      tickingClock: "NA",
      stakes: "NA",
      goal: "NA",
      cliffhanger: "NA",
      note: "NA",
    },
    {
      code: "I0010",
      show: "MVS",
      angle: "The Neuroscience of Storytelling and Why It Drives Action",
      submittedByName: "Joshua Roth",
      submittedOn: "2026-01-14",
      status: IdeaStatus.ACCEPTED,
      rank: IdeaRank.HIGH_CONVICTION,
      setting: "Neuroscience meets communication strategy",
      opening: "The stories that move people aren't random — they're engineered",
      tickingClock: "In the attention economy forgettable content is wasted",
      stakes: "Influence, brand memory, audience retention",
      goal: "Map narrative structure to emotional memory formation",
      cliffhanger: "What's the story your audience remembers in 10 years?",
      note: "NA",
    },
  ];

  const ideaIdByCode = new Map<string, string>();

  for (const idea of ideas) {
    const createdIdea = await prisma.idea.create({
      data: {
        code: idea.code,
        show: idea.show,
        angle: idea.angle,
        submittedById: personByName.get(idea.submittedByName)!,
        submittedOn: dateOnly(idea.submittedOn),
        status: idea.status,
        rank: idea.rank,
        setting: idea.setting,
        opening: idea.opening,
        tickingClock: idea.tickingClock,
        stakes: idea.stakes,
        goal: idea.goal,
        cliffhanger: idea.cliffhanger,
        note: idea.note,
      },
    });

    ideaIdByCode.set(idea.code, createdIdea.id);
  }

  const beats = [
    {
      code: "B0001",
      ideaCode: "I0001",
      title: "Sleep & Cortisol — The Performance Link",
      setting: "Corporate office",
      opening: "Most people treat sleep as optional — their cortisol tells a different story",
      tickingClock: "Every poor night compounds measurable performance loss",
      stakes: "Decision quality, focus, emotional regulation",
      goal: "Connect sleep science to workplace productivity",
      cliffhanger: "What if sleep is your biggest untapped productivity hack?",
      note: "NA",
      docLink: "https://docs.google.com/mock-b1",
      assignedToName: "Jonathan Hernandez",
      assignedRole: BeatAssigneeRole.WRITER,
      requestRaisedOn: "2026-01-10",
      expectedStartDate: "2026-01-11",
      expectedCompleteDate: "2026-01-14",
      status: BeatStatus.APPROVED_FOR_SCRIPT_WRITING,
      submittedOn: "2026-01-13",
      reviewedByName: "Dan Woodward",
      reviewedOn: "2026-01-14",
      reviewNotes: "",
    },
    {
      code: "B0002",
      ideaCode: "I0001",
      title: "Sleep Debt and Decision Making",
      setting: "High-stakes decisions",
      opening: "Every sleepless night costs you more than energy",
      tickingClock: "Sleep debt compounds 30% faster than most realise",
      stakes: "Strategic decisions, team morale, personal health",
      goal: "Quantify the decision-making cost of sleep deprivation",
      cliffhanger: "How many wrong calls have you made sleep-deprived?",
      note: "NA",
      docLink: "https://docs.google.com/mock-b2",
      assignedToName: "Ari Jacobson",
      assignedRole: BeatAssigneeRole.WRITER,
      requestRaisedOn: "2026-01-10",
      expectedStartDate: "2026-01-12",
      expectedCompleteDate: "2026-01-14",
      status: BeatStatus.APPROVED_FOR_SCRIPT_WRITING,
      submittedOn: "2026-01-13",
      reviewedByName: "Dan Woodward",
      reviewedOn: "2026-01-14",
      reviewNotes: "",
    },
    {
      code: "B0003",
      ideaCode: "I0002",
      title: "Always-On Culture and Burnout",
      setting: "Remote/hybrid work",
      opening: "The notification that never stops is rewiring your brain",
      tickingClock: "Burnout rates are doubling year over year",
      stakes: "Mental health, team retention, creative output",
      goal: "Connect always-on culture to measurable burnout",
      cliffhanger: "What if you turned off notifications for 72 hours?",
      note: "NA",
      docLink: "https://docs.google.com/mock-b3",
      assignedToName: "Nandita Seshadri",
      assignedRole: BeatAssigneeRole.WRITER,
      requestRaisedOn: "2026-01-11",
      expectedStartDate: "2026-01-12",
      expectedCompleteDate: "2026-01-15",
      status: BeatStatus.APPROVED_FOR_SCRIPT_WRITING,
      submittedOn: "2026-01-14",
      reviewedByName: "Joshua Roth",
      reviewedOn: "2026-01-15",
      reviewNotes: "",
    },
    {
      code: "B0004",
      ideaCode: "I0006",
      title: "Cold Exposure and the Nervous System",
      setting: "Biohacking / wellness",
      opening: "Your body has a built-in stress reset button",
      tickingClock: "Chronic stress is degrading nervous system resilience daily",
      stakes: "Mental resilience, physical recovery, stress response",
      goal: "Explain cold exposure's effect on the vagus nerve",
      cliffhanger: "Could 3 minutes of cold water change your stress response?",
      note: "NA",
      docLink: null,
      assignedToName: "Miguel Silan",
      assignedRole: BeatAssigneeRole.WRITER,
      requestRaisedOn: "2026-01-13",
      expectedStartDate: "2026-01-15",
      expectedCompleteDate: "2026-01-20",
      status: BeatStatus.SUBMITTED,
      submittedOn: "2026-01-19",
      reviewedByName: null,
      reviewedOn: null,
      reviewNotes: "",
    },
    {
      code: "B0005",
      ideaCode: "I0006",
      title: "Voluntary Discomfort as a Resilience Tool",
      setting: "Personal development",
      opening: "Comfort is the enemy of growth — but how do you train discomfort?",
      tickingClock: "Every avoided challenge makes the next one harder",
      stakes: "Mental toughness, grit, long-term resilience",
      goal: "Build the case for voluntary discomfort as deliberate practice",
      cliffhanger: "What's the one uncomfortable thing you've been avoiding?",
      note: "NA",
      docLink: "https://docs.google.com/mock-b5",
      assignedToName: "Will Morgan",
      assignedRole: BeatAssigneeRole.WRITER,
      requestRaisedOn: "2026-01-13",
      expectedStartDate: "2026-01-15",
      expectedCompleteDate: "2026-01-20",
      status: BeatStatus.APPROVED_FOR_SCRIPT_WRITING,
      submittedOn: "2026-01-18",
      reviewedByName: "Paul Lee",
      reviewedOn: "2026-01-20",
      reviewNotes: "",
    },
    {
      code: "B0006",
      ideaCode: "I0010",
      title: "Story Structure and Emotional Memory",
      setting: "Neuroscience / communication",
      opening: "The stories that stay aren't random — they're engineered",
      tickingClock: "In the attention economy forgettable content is wasted",
      stakes: "Influence, retention, brand memory",
      goal: "Map narrative structure to emotional memory formation",
      cliffhanger: "What's the story your audience remembers in 10 years?",
      note: "NA",
      docLink: "https://docs.google.com/mock-b6",
      assignedToName: "Jasper Chen",
      assignedRole: BeatAssigneeRole.WRITER,
      requestRaisedOn: "2026-01-14",
      expectedStartDate: "2026-01-16",
      expectedCompleteDate: "2026-01-21",
      status: BeatStatus.APPROVED_FOR_SCRIPT_WRITING,
      submittedOn: "2026-01-20",
      reviewedByName: "Joshua Roth",
      reviewedOn: "2026-01-21",
      reviewNotes: "",
    },
    {
      code: "B0007",
      ideaCode: "I0004",
      title: "Habit Stacking for Behavioral Change",
      setting: "Behavioral psychology",
      opening: "You don't build habits — you stack them",
      tickingClock: "Every day without a system is lost momentum",
      stakes: "Long-term behavior change, personal effectiveness",
      goal: "Explain habit stacking with practical examples",
      cliffhanger: "What's the one habit that could unlock five others?",
      note: "NA",
      docLink: null,
      assignedToName: "Micah McFarland",
      assignedRole: BeatAssigneeRole.WRITER,
      requestRaisedOn: "2026-01-15",
      expectedStartDate: "2026-01-18",
      expectedCompleteDate: "2026-01-24",
      status: BeatStatus.ASSIGNED,
      submittedOn: null,
      reviewedByName: null,
      reviewedOn: null,
      reviewNotes: "",
    },
    {
      code: "B0008",
      ideaCode: "I0008",
      title: "Deliberate Practice vs Repetition",
      setting: "Skill development",
      opening: "Repetition doesn't make you better — deliberate practice does",
      tickingClock: "Most people plateau because they confuse volume with progress",
      stakes: "Career growth, skill mastery, competitive advantage",
      goal: "Distinguish deliberate practice from mere repetition",
      cliffhanger: "Are you practicing — or just going through the motions?",
      note: "NA",
      docLink: null,
      assignedToName: "Carolina Munhoz",
      assignedRole: BeatAssigneeRole.WRITER,
      requestRaisedOn: "2026-01-16",
      expectedStartDate: "2026-01-20",
      expectedCompleteDate: "2026-01-27",
      status: BeatStatus.TO_BE_REDONE,
      submittedOn: "2026-01-24",
      reviewedByName: "Dan Woodward",
      reviewedOn: "2026-01-25",
      reviewNotes: "Opening angle needs more punch. Ticking clock is too generic.",
    },
  ];

  const beatIdByCode = new Map<string, string>();

  for (const beat of beats) {
    const createdBeat = await prisma.beat.create({
      data: {
        code: beat.code,
        ideaId: ideaIdByCode.get(beat.ideaCode)!,
        title: beat.title,
        setting: beat.setting,
        opening: beat.opening,
        tickingClock: beat.tickingClock,
        stakes: beat.stakes,
        goal: beat.goal,
        cliffhanger: beat.cliffhanger,
        note: beat.note,
        docLink: beat.docLink,
        assignedToId: personByName.get(beat.assignedToName)!,
        assignedRole: beat.assignedRole,
        requestRaisedOn: dateOnly(beat.requestRaisedOn),
        expectedStartDate: dateOnly(beat.expectedStartDate),
        expectedCompleteDate: dateOnly(beat.expectedCompleteDate),
        status: beat.status,
        submittedOn: beat.submittedOn ? dateOnly(beat.submittedOn) : null,
        reviewedById: beat.reviewedByName ? personByName.get(beat.reviewedByName)! : null,
        reviewedOn: beat.reviewedOn ? dateOnly(beat.reviewedOn) : null,
        reviewNotes: beat.reviewNotes,
      },
    });

    beatIdByCode.set(beat.code, createdBeat.id);
  }

  const assignments = [
    {
      code: "GA00001",
      assignmentType: AssignmentType.NEW,
      beatCode: "B0001",
      show: "MVS",
      angle: "Sleep & Cortisol — The Performance Link",
      writerName: "Jonathan Hernandez",
      podLeadName: "Dan Woodward",
      dateAssigned: "2026-01-10",
      dateDue: "2026-01-17",
      notes: "Focus on the opening hook.",
      status: AssignmentStatus.READY_FOR_PRODUCTION,
      submission: "Draft with strong narrative arc.",
      grade: AssignmentGrade.STRONG_OUTPUT,
      feedback: "Tighten the final paragraph.",
      finalOutput: "Polished version with tightened conclusion.",
      prodSuffix: ProductionType.GA,
      submittedAt: "2026-01-14T10:22:00.000Z",
      reviewedAt: "2026-01-16T15:45:00.000Z",
      productionReadyAt: "2026-01-16T15:45:00.000Z",
      parentCode: null,
      editCode: "GA1001",
      codeToRework: null,
      updatedBeats: null,
    },
    {
      code: "GU00002",
      assignmentType: AssignmentType.NEW,
      beatCode: "B0003",
      show: "FLBM",
      angle: "Always-On Culture and Burnout",
      writerName: "Nandita Seshadri",
      podLeadName: "Joshua Roth",
      dateAssigned: "2026-01-11",
      dateDue: "2026-01-18",
      notes: "Conversational tone, not academic.",
      status: AssignmentStatus.READY_FOR_PRODUCTION,
      submission: "Well-paced piece with strong voice.",
      grade: AssignmentGrade.STRONG_OUTPUT,
      feedback: "Solid. Minor wording edits applied.",
      finalOutput: "Final version with two minor phrasing adjustments.",
      prodSuffix: ProductionType.GU,
      submittedAt: "2026-01-15T09:10:00.000Z",
      reviewedAt: "2026-01-17T11:30:00.000Z",
      productionReadyAt: "2026-01-17T11:30:00.000Z",
      parentCode: null,
      editCode: "GU2034",
      codeToRework: null,
      updatedBeats: null,
    },
    {
      code: "00003",
      assignmentType: AssignmentType.IMPROVEMENT,
      beatCode: null,
      show: "WBT",
      angle: "Decision Fatigue — Second Pass",
      writerName: "Miguel Silan",
      podLeadName: "Paul Lee",
      dateAssigned: "2026-01-12",
      dateDue: "2026-01-20",
      notes: "Ensure logical flow between beats 2 and 3.",
      status: AssignmentStatus.REWRITE_REQUIRED,
      submission: "Draft with structural issues in middle section.",
      grade: AssignmentGrade.MAJOR_FLAWS,
      feedback: "The transition between conflict and resolution needs a full rework.",
      finalOutput: "Reviewed version with comments inline.",
      prodSuffix: null,
      submittedAt: "2026-01-18T14:15:00.000Z",
      reviewedAt: "2026-01-20T16:00:00.000Z",
      productionReadyAt: null,
      parentCode: null,
      editCode: "GA4422",
      codeToRework: "GA3300",
      updatedBeats: "https://docs.google.com/mock-update1",
    },
    {
      code: "00004",
      assignmentType: AssignmentType.NEW,
      beatCode: "B0005",
      show: "WBT",
      angle: "Voluntary Discomfort as a Resilience Tool",
      writerName: "Will Morgan",
      podLeadName: "Nishant Gilatar",
      dateAssigned: "2026-01-13",
      dateDue: "2026-01-21",
      notes: "Opening idea must be punchy.",
      status: AssignmentStatus.ASSIGNED_TO_WRITER,
      submission: null,
      grade: null,
      feedback: null,
      finalOutput: null,
      prodSuffix: null,
      submittedAt: null,
      reviewedAt: null,
      productionReadyAt: null,
      parentCode: null,
      editCode: "GU8801",
      codeToRework: null,
      updatedBeats: null,
    },
    {
      code: "GU00005",
      assignmentType: AssignmentType.NEW,
      beatCode: "B0002",
      show: "MVS",
      angle: "Sleep Debt and Decision Making",
      writerName: "Ari Jacobson",
      podLeadName: "Dan Woodward",
      dateAssigned: "2026-01-14",
      dateDue: "2026-01-22",
      notes: "Balance humor with information.",
      status: AssignmentStatus.READY_FOR_PRODUCTION,
      submission: "Clean draft with great pacing.",
      grade: AssignmentGrade.STRONG_OUTPUT,
      feedback: "One sentence trimmed in the body.",
      finalOutput: "Final version with light edits to mid-section.",
      prodSuffix: ProductionType.GU,
      submittedAt: "2026-01-19T08:55:00.000Z",
      reviewedAt: "2026-01-21T14:10:00.000Z",
      productionReadyAt: "2026-01-21T14:10:00.000Z",
      parentCode: null,
      editCode: "GU3310",
      codeToRework: null,
      updatedBeats: null,
    },
    {
      code: "00006",
      assignmentType: AssignmentType.IMPROVEMENT,
      beatCode: null,
      show: "FLBM",
      angle: "Burnout Culture — Deeper Dive",
      writerName: "Krystle Drew",
      podLeadName: "Joshua Roth",
      dateAssigned: "2026-01-15",
      dateDue: "2026-01-23",
      notes: "Strong CTA at the end.",
      status: AssignmentStatus.COMPLETED_BY_WRITER,
      submission: "Submitted with compelling CTA and tight body copy.",
      grade: null,
      feedback: null,
      finalOutput: null,
      prodSuffix: null,
      submittedAt: "2026-01-21T11:40:00.000Z",
      reviewedAt: null,
      productionReadyAt: null,
      parentCode: null,
      editCode: "GA5599",
      codeToRework: "GU00002",
      updatedBeats: "https://docs.google.com/mock-update2",
    },
    {
      code: "00007",
      assignmentType: AssignmentType.NEW,
      beatCode: "B0006",
      show: "MVS",
      angle: "Story Structure and Emotional Memory",
      writerName: "Jasper Chen",
      podLeadName: "Paul Lee",
      dateAssigned: "2026-01-15",
      dateDue: "2026-01-24",
      notes: "Avoid passive voice throughout.",
      status: AssignmentStatus.ASSIGNED_TO_WRITER,
      submission: null,
      grade: null,
      feedback: null,
      finalOutput: null,
      prodSuffix: null,
      submittedAt: null,
      reviewedAt: null,
      productionReadyAt: null,
      parentCode: null,
      editCode: "GU7721",
      codeToRework: null,
      updatedBeats: null,
    },
    {
      code: "GA00008",
      assignmentType: AssignmentType.NEW,
      beatCode: "B0001",
      show: "MVS",
      angle: "Sleep & Cortisol — Short Form",
      writerName: "Carolina Munhoz",
      podLeadName: "Dan Woodward",
      dateAssigned: "2026-01-16",
      dateDue: "2026-01-25",
      notes: "Research-heavy — cite at least 3 data points.",
      status: AssignmentStatus.REWRITE_REQUIRED,
      submission: "Draft missing supporting data in section 3.",
      grade: AssignmentGrade.MINOR_FLAWS,
      feedback: "Opening idea falls flat. Rework the angle.",
      finalOutput: "",
      prodSuffix: null,
      submittedAt: "2026-01-22T15:30:00.000Z",
      reviewedAt: "2026-01-24T10:15:00.000Z",
      productionReadyAt: null,
      parentCode: null,
      editCode: "GA2200",
      codeToRework: null,
      updatedBeats: null,
    },
    {
      code: "GA00009",
      assignmentType: AssignmentType.NEW,
      beatCode: "B0005",
      show: "WBT",
      angle: "Voluntary Discomfort — Long Form",
      writerName: "Micah McFarland",
      podLeadName: "Nishant Gilatar",
      dateAssigned: "2026-01-17",
      dateDue: "2026-01-26",
      notes: "Match the tone of the existing series.",
      status: AssignmentStatus.READY_FOR_PRODUCTION,
      submission: "Polished draft consistent with series voice.",
      grade: AssignmentGrade.STRONG_OUTPUT,
      feedback: "Minor punctuation edits only.",
      finalOutput: "Final version ready.",
      prodSuffix: ProductionType.GA,
      submittedAt: "2026-01-23T09:00:00.000Z",
      reviewedAt: "2026-01-25T13:20:00.000Z",
      productionReadyAt: "2026-01-25T13:20:00.000Z",
      parentCode: null,
      editCode: "GA1188",
      codeToRework: null,
      updatedBeats: null,
    },
    {
      code: "00010",
      assignmentType: AssignmentType.IMPROVEMENT,
      beatCode: null,
      show: "WBT",
      angle: "Decision Fatigue — Revised Angle",
      writerName: "Joe Osborn",
      podLeadName: "Joshua Roth",
      dateAssigned: "2026-01-18",
      dateDue: "2026-01-27",
      notes: "Second draft — address pacing notes.",
      status: AssignmentStatus.ASSIGNED_TO_WRITER,
      submission: null,
      grade: null,
      feedback: null,
      finalOutput: null,
      prodSuffix: null,
      submittedAt: null,
      reviewedAt: null,
      productionReadyAt: null,
      parentCode: "00003",
      editCode: "GU9900",
      codeToRework: "00003",
      updatedBeats: "https://docs.google.com/mock-update3",
    },
  ];

  const assignmentIdByCode = new Map<string, string>();

  for (const assignment of assignments.filter((item) => item.parentCode === null)) {
    const createdAssignment = await prisma.assignment.create({
      data: {
        code: assignment.code,
        assignmentType: assignment.assignmentType,
        beatId: assignment.beatCode ? beatIdByCode.get(assignment.beatCode)! : null,
        show: assignment.show,
        angle: assignment.angle,
        writerId: personByName.get(assignment.writerName)!,
        podLeadId: personByName.get(assignment.podLeadName)!,
        dateAssigned: dateOnly(assignment.dateAssigned),
        dateDue: dateOnly(assignment.dateDue),
        notes: assignment.notes,
        status: assignment.status,
        submission: assignment.submission,
        grade: assignment.grade,
        feedback: assignment.feedback,
        finalOutput: assignment.finalOutput,
        prodSuffix: assignment.prodSuffix,
        submittedAt: assignment.submittedAt ? timestamp(assignment.submittedAt) : null,
        reviewedAt: assignment.reviewedAt ? timestamp(assignment.reviewedAt) : null,
        productionReadyAt: assignment.productionReadyAt ? timestamp(assignment.productionReadyAt) : null,
        editCode: assignment.editCode,
        codeToRework: assignment.codeToRework,
        updatedBeats: assignment.updatedBeats,
      },
    });

    assignmentIdByCode.set(assignment.code, createdAssignment.id);
  }

  for (const assignment of assignments.filter((item) => item.parentCode !== null)) {
    const createdAssignment = await prisma.assignment.create({
      data: {
        code: assignment.code,
        assignmentType: assignment.assignmentType,
        beatId: assignment.beatCode ? beatIdByCode.get(assignment.beatCode)! : null,
        show: assignment.show,
        angle: assignment.angle,
        writerId: personByName.get(assignment.writerName)!,
        podLeadId: personByName.get(assignment.podLeadName)!,
        dateAssigned: dateOnly(assignment.dateAssigned),
        dateDue: dateOnly(assignment.dateDue),
        notes: assignment.notes,
        status: assignment.status,
        submission: assignment.submission,
        grade: assignment.grade,
        feedback: assignment.feedback,
        finalOutput: assignment.finalOutput,
        prodSuffix: assignment.prodSuffix,
        submittedAt: assignment.submittedAt ? timestamp(assignment.submittedAt) : null,
        reviewedAt: assignment.reviewedAt ? timestamp(assignment.reviewedAt) : null,
        productionReadyAt: assignment.productionReadyAt ? timestamp(assignment.productionReadyAt) : null,
        parentAssignmentId: assignment.parentCode ? assignmentIdByCode.get(assignment.parentCode)! : null,
        editCode: assignment.editCode,
        codeToRework: assignment.codeToRework,
        updatedBeats: assignment.updatedBeats,
      },
    });

    assignmentIdByCode.set(assignment.code, createdAssignment.id);
  }
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (error) => {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  });
